### ISSUE TITLE
I want to add Korean to the CSE2 game

### ISSUE THREAD

**Issue by flashkiller81** [IruzzArcana/CSE2-vita#1]
Hello IruzzArcana,
I'm not good at English, so I'll convey my meaning in Japanese.

まずは連絡先が知らないので、この掲示板に書かせていただきます。
僕は韓国のプログラマーであるflashkillerと申します。
Iruzzさんの作ってくれたCSE2-Vitaを見てこのゲームは日本語で楽しめるから韓国語も追加させてほしいって思いました。
もちろん韓国語の変換は僕がやらせていただきますが、
フォルダの中にイメージとかフォントとか見えますが、ファイルを開いてみてもどこをどうやって修正すればセリフのテキストが変わるのか分かりません。
できればセリフのテキスト出力のやり方について教えていただけますか。フォントとかイメージが必要だったら直接作ります。ぜひお願いいたします。
ご返信楽しみに待っています。(flashkiller@naver.com)

今日も良い一日をお過ごしください。

**Comment by IruzzArcana** [comment]
はじめに、私の日本語は下手です、ごめんなさい、そして英語は説明します。

The game actually doesn't use the .png and .dat files in that folder, it simply loads the file called "font" which is just a .ttf file that you can replace with anything you want, though you'd probably need to adjust the width/height as those are hard-coded [here](https://github.com/gameblabla/CSE2/blob/b9d9d339f831672710235330064902317a35e838/src/Draw.cpp#L720), as for how to translate the game to Korean, this is done by modifying .tsc files which are encrypted plain-text files, you can use [this script](https://gist.github.com/fdeitylink/18ddc14f3a716cbecad6510bb3c3dc2a) to decrypt them and vice-versa, as for the map names, they're hard-coded [here](https://github.com/gameblabla/CSE2/blob/b9d9d339f831672710235330064902317a35e838/src/Stage.cpp#L40).
Now here comes the tricky part:
The way CSE2 handles non-unicode characters is rather... _unique_. For instance, [this is how it handles Japanese characters](https://github.com/gameblabla/CSE2/blob/b9d9d339f831672710235330064902317a35e838/src/Font.cpp#L74).
Now unfortunately I can't exactly give you any advice on how you can pull that off with EUC-KR as I'm not too familiar with 
character encodings and whatnot, sorry.

Hopefully this might have helped you clear some things up, good luck with your translation project.

**Comment by flashkiller81** [comment]
Thank you very much for your cooperation.
I will try this project, but I don't know how long years.
Have a nice day!

**Comment by flashkiller81** [comment]
Hello, it's been a while.
I'd like to share the results of the Korean localization I mentioned earlier.
I completed the Korean localization using the CSE2 source code and your comments.
The URL link below shows the results of the Korean localization for the Vita version.
Thanks to IruzzArcana, I'm happy to have completed the Korean localization. Thank you.

https://blog.naver.com/flashkiller/224121471916

**Comment by IruzzArcana** [comment]
Congrats! Glad I could help somehow :)
